CREATE TABLE `sys_message_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `template_id` bigint DEFAULT NULL COMMENT '模板ID',
  `template_code` varchar(64) DEFAULT NULL COMMENT '模板编码',
  `channel` tinyint NOT NULL COMMENT '渠道 1-短信 2-站内通知 3-公众号模板消息 4-小程序订阅消息',
  `recipient` varchar(200) NOT NULL COMMENT '接收人（用户ID/手机号/OpenID）',
  `title` varchar(500) DEFAULT NULL COMMENT '标题（变量已替换）',
  `content` text COMMENT '内容（变量已替换）',
  `params` json DEFAULT NULL COMMENT '发送参数JSON',
  `send_status` tinyint NOT NULL DEFAULT '0' COMMENT '发送状态 0-待发送 1-成功 2-失败',
  `read_status` tinyint NOT NULL DEFAULT '0' COMMENT '阅读状态 0-未读 1-已读（仅站内信）',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `biz_module` varchar(50) DEFAULT NULL COMMENT '业务模块',
  `biz_key` varchar(100) DEFAULT NULL COMMENT '业务标识',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_send_status` (`send_status`),
  KEY `idx_recipient` (`recipient`),
  KEY `idx_biz` (`biz_module`,`biz_key`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='消息发送记录表';